server:
  port: 8080

spring:
  application:
    name: ecommerce-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce
      database: ecommerce

logging:
  level:
    com.example.ecommerce: DEBUG
